HawkesTHP_eval:
  base_config:
    backend: torch
    base_dir: ./checkpoints/
    dataset_id: mimic
    model_id: HawkesTHP
    runner_id: std_tpp
    stage: eval
  model_config:
    d_k: 10
    d_model: 10
    d_rnn: 10
    d_v: 10
    hidden_size: 64
    loss_integral_num_sample_per_step: 1000
    mc_num_sample_per_step: 1000
    num_heads: 2
    num_layers: 2
    phi_depth: 2
    phi_width: 4
    pretrained_model_dir: ./checkpoints/16072_25432_250721-020250\models\saved_model
    rnn: True
    thinning:
      dtime_max: 5
      look_ahead_time: 10
      num_exp: 500
      num_sample: 1000
      num_samples_boundary: 5
      num_seq: 10
      num_step_gen: 1
      over_sample_rate: 5
      patience_counter: 5
    time_emb_size: 4
    use_ln: true
  trainer_config:
    batch_size: 32
    gpu: -1
    l2_coef: 0.1
    learning_rate: 0.01
    max_epoch: 2
    metrics:
    - acc
    - rmse
    optimizer: adam
    seed: 2025
    shuffle: false
    use_tfb: false
    valid_freq: 1

THP_eval:
  base_config:
    backend: torch
    base_dir: ./checkpoints/
    dataset_id: mimic
    model_id: THP
    runner_id: std_tpp
    stage: eval
  model_config:
    d_k: 64
    d_model: 64
    d_rnn: 64
    d_v: 64
    hidden_size: 64
    loss_integral_num_sample_per_step: 1000
    mc_num_sample_per_step: 1000
    num_heads: 2
    num_layers: 2
    phi_depth: 2
    phi_width: 4
    pretrained_model_dir: ./checkpoints/25076_13004_250721-021836\models\saved_model
    rnn: True
    thinning:
      dtime_max: 5
      look_ahead_time: 10
      num_exp: 500
      num_sample: 1000
      num_samples_boundary: 5
      num_seq: 10
      num_step_gen: 1
      over_sample_rate: 5
      patience_counter: 5
    time_emb_size: 4
    use_ln: true
  trainer_config:
    batch_size: 256
    gpu: -1
    l2_coef: 0.1
    learning_rate: 0.01
    max_epoch: 2
    metrics:
    - acc
    - rmse
    optimizer: adam
    seed: 2025
    shuffle: false
    use_tfb: false
    valid_freq: 1
data:
  mimic:
    data_format: pkl
    data_specs:
      num_event_types: 75
      pad_token_id: 75
      padding_side: right
      truncation_side: right
    test_dir: ./data/data_mimic/all/test.pkl
    train_dir: ./data/data_mimic/all/train.pkl
    valid_dir: ./data/data_mimic/all/dev.pkl
pipeline_config_id: runner_config
