HawkesTHP_eval:
  base_config:
    backend: torch
    base_dir: ./checkpoints/
    dataset_id: retweet
    model_id: HawkesTHP
    runner_id: std_tpp
    stage: eval
  model_config:
    d_k: 3
    d_model: 3
    d_rnn: 3
    d_v: 3
    hidden_size: 8
    loss_integral_num_sample_per_step: 20
    mc_num_sample_per_step: 20
    num_heads: 1
    num_layers: 1
    phi_depth: 2
    phi_width: 8
    pretrained_model_dir: ./checkpoints/26507_4380788096_231111-101848/models/saved_model
    rnn: true
    thinning:
      dtime_max: 5
      look_ahead_time: 10
      num_exp: 500
      num_sample: 1000
      num_samples_boundary: 5
      num_seq: 10
      num_step_gen: 1
      over_sample_rate: 5
      patience_counter: 5
    time_emb_size: 4
    use_ln: false
  trainer_config:
    batch_size: 64
    gpu: 0
    l2_coef: 0.1
    learning_rate: 0.001
    max_epoch: 2
    metrics:
    - acc
    - rmse
    optimizer: adam
    seed: 2025
    shuffle: false
    use_tfb: false
    valid_freq: 1
THP_eval:
  base_config:
    backend: torch
    base_dir: ./checkpoints/
    dataset_id: retweet
    model_id: THP
    runner_id: std_tpp
    stage: eval
  model_config:
    hidden_size: 64
    loss_integral_num_sample_per_step: 20
    mc_num_sample_per_step: 20
    num_heads: 2
    num_layers: 2
    pretrained_model_dir: ./checkpoints/3484_27888_250721-235837\models\saved_model
    thinning:
      dtime_max: 5
      look_ahead_time: 10
      num_exp: 500
      num_sample: 1
      num_samples_boundary: 5
      num_seq: 10
      num_step_gen: 1
      over_sample_rate: 5
      patience_counter: 5
    time_emb_size: 16
    use_ln: false
  trainer_config:
    batch_size: 256
    gpu: 0
    learning_rate: 0.001
    max_epoch: 30
    metrics:
    - acc
    - rmse
    optimizer: adam
    seed: 2019
    shuffle: false
    use_tfb: false
    valid_freq: 1
data:
  retweet:
    data_format: json
    data_specs:
      num_event_types: 3
      pad_token_id: 3
      padding_side: right
      truncation_side: right
    test_dir: easytpp/retweet
    train_dir: easytpp/retweet
    valid_dir: easytpp/retweet
pipeline_config_id: runner_config
