pipeline_config_id: runner_config

data:
  mimic:
    data_format: pkl
    train_dir: ./data/data_mimic/all/train.pkl
    valid_dir: ./data/data_mimic/all/dev.pkl
    test_dir: ./data/data_mimic/all/test.pkl
    data_specs:
      num_event_types: 75
      pad_token_id: 75
      padding_side: right
      truncation_side: right


  
HawkesTHP_train:
  base_config:
    stage: train
    backend: torch
    dataset_id: mimic
    runner_id: std_tpp
    model_id: HawkesTHP # model name
    base_dir: './checkpoints/'
  trainer_config:
    batch_size: 32
    max_epoch: 200
    shuffle: False
    optimizer: adam
    learning_rate: 1.e-2
    valid_freq: 1
    use_tfb: False
    metrics: [ 'acc', 'rmse' ]
    seed: 2025
    gpu: 0
    l2_coef: 0.1
  model_config:
    hidden_size: 64
    time_emb_size: 4
    num_layers: 2
    num_heads: 2
    phi_width: 4
    phi_depth: 2
    d_k: 10
    d_v: 10
    d_model: 10
    d_rnn: 10
    rnn: True
    mc_num_sample_per_step: 1000
    loss_integral_num_sample_per_step: 1000
    use_ln: True
    dropout_rate: 0.1
    thinning:
      num_seq: 10
      num_sample: 1000
      num_exp: 500 # number of i.i.d. Exp(intensity_bound) draws at one time in thinning algorithm
      look_ahead_time: 10
      patience_counter: 5 # the maximum iteration used in adaptive thinning
      over_sample_rate: 5
      num_samples_boundary: 5
      dtime_max: 5
      num_step_gen: 1


HawkesTHP_gen:
  base_config:
    stage: gen
    backend: torch
    dataset_id: mimic
    runner_id: std_tpp
    model_id: HawkesTHP # model name
    base_dir: './checkpoints/'
  trainer_config:
    batch_size: 1
    max_epoch: 1
  model_config:
    hidden_size: 64
    time_emb_size: 4
    num_layers: 2
    num_heads: 2
    phi_width: 4
    phi_depth: 2
    d_k: 10
    d_v: 10
    d_model: 10
    d_rnn: 10
    rnn: True
    mc_num_sample_per_step: 1000
    loss_integral_num_sample_per_step: 1000
    use_ln: True
    dropout_rate: 0.1
    thinning:
      num_seq: 10
      num_sample: 1000
      num_exp: 500 # number of i.i.d. Exp(intensity_bound) draws at one time in thinning algorithm
      look_ahead_time: 10
      patience_counter: 5 # the maximum iteration used in adaptive thinning
      over_sample_rate: 5
      num_samples_boundary: 5
      dtime_max: 5
      num_step_gen: 1


THP_train:
  base_config:
    stage: train
    backend: torch
    dataset_id: mimic
    runner_id: std_tpp
    model_id: THP # model name
    base_dir: './checkpoints/'
  trainer_config:
    batch_size: 256
    max_epoch: 200
    shuffle: False
    optimizer: adam
    learning_rate: 1.e-2
    valid_freq: 1
    use_tfb: False
    metrics: [ 'acc', 'rmse' ]
    seed: 2025
    gpu: 0
    l2_coef: 0.1
  model_config:
    hidden_size: 64
    time_emb_size: 16
    num_layers: 2
    num_heads: 2
    d_k: 64
    d_v: 64
    d_model: 64
    d_rnn: 10
    rnn: True
    mc_num_sample_per_step: 1000
    loss_integral_num_sample_per_step: 1000
    use_ln: True
    thinning:
      num_seq: 10
      num_sample: 1000
      num_exp: 500 # number of i.i.d. Exp(intensity_bound) draws at one time in thinning algorithm
      look_ahead_time: 10
      patience_counter: 5 # the maximum iteration used in adaptive thinning
      over_sample_rate: 5
      num_samples_boundary: 5
      dtime_max: 5
      num_step_gen: 1


THP_gen:
  base_config:
    stage: gen
    backend: torch
    dataset_id: mimic
    runner_id: std_tpp
    model_id: THP # model name
    base_dir: './checkpoints/'
  trainer_config:
    batch_size: 256
    max_epoch: 1
  model_config:
    hidden_size: 64
    time_emb_size: 16
    num_layers: 2
    num_heads: 2
    d_k: 64
    d_v: 64
    d_model: 64
    d_rnn: 64
    rnn: True
    mc_num_sample_per_step: 1000
    loss_integral_num_sample_per_step: 1000
    use_ln: True
    thinning:
      num_seq: 10
      num_sample: 1000
      num_exp: 500 # number of i.i.d. Exp(intensity_bound) draws at one time in thinning algorithm
      look_ahead_time: 10
      patience_counter: 5 # the maximum iteration used in adaptive thinning
      over_sample_rate: 5
      num_samples_boundary: 5
      dtime_max: 5
      num_step_gen: 1