pipeline_config_id: runner_config

data:
  stackoverflow:
    data_format: json
    train_dir: easytpp/stackoverflow
    valid_dir: easytpp/stackoverflow
    test_dir: easytpp/stackoverflow
    data_specs:
      num_event_types: 22
      pad_token_id: 22
      padding_side: right
      truncation_side: right


  
HawkesTHP_train:
  base_config:
    stage: train
    backend: torch
    dataset_id: stackoverflow
    runner_id: std_tpp
    model_id: HawkesTHP # model name
    base_dir: './checkpoints/'
  trainer_config:
    batch_size: 64
    max_epoch: 500
    shuffle: False
    optimizer: adam
    learning_rate: 1.e-3
    valid_freq: 1
    use_tfb: False
    metrics: [ 'acc', 'rmse' ]
    seed: 2025
    gpu: 0
    l2_coef: 0.1
  model_config:
    hidden_size: 64
    time_emb_size: 4
    num_layers: 2
    num_heads: 2
    phi_width: 8
    phi_depth: 2
    d_k: 32
    d_v: 32
    d_model: 32
    d_rnn: 32
    rnn: True
    mc_num_sample_per_step: 20
    loss_integral_num_sample_per_step: 20
    use_ln: True
    dropout_rate: 0.1
    thinning:
      num_seq: 10
      num_sample: 1
      num_exp: 500 # number of i.i.d. Exp(intensity_bound) draws at one time in thinning algorithm
      look_ahead_time: 10
      patience_counter: 5 # the maximum iteration used in adaptive thinning
      over_sample_rate: 5
      num_samples_boundary: 5
      dtime_max: 5
      num_step_gen: 1


HawkesTHP_gen:
  base_config:
    stage: gen
    backend: torch
    dataset_id: stackoverflow
    runner_id: std_tpp
    model_id: HawkesTHP # model name
    base_dir: './checkpoints/'
  trainer_config:
    batch_size: 64
    max_epoch: 1
  model_config:
    hidden_size: 64
    time_emb_size: 4
    num_layers: 2
    num_heads: 2
    phi_width: 8
    phi_depth: 2
    d_k: 32
    d_v: 32
    d_model: 32
    d_rnn: 32
    rnn: True
    mc_num_sample_per_step: 20
    loss_integral_num_sample_per_step: 20
    use_ln: True
    dropout_rate: 0.1
    thinning:
      num_seq: 10
      num_sample: 1
      num_exp: 500 # number of i.i.d. Exp(intensity_bound) draws at one time in thinning algorithm
      look_ahead_time: 10
      patience_counter: 5 # the maximum iteration used in adaptive thinning
      over_sample_rate: 5
      num_samples_boundary: 5
      dtime_max: 5
      num_step_gen: 1


THP_train:
  base_config:
    stage: train
    backend: torch
    dataset_id: taxi
    runner_id: std_tpp
    model_id: THP # model name
    base_dir: './checkpoints/'
  trainer_config:
    batch_size: 256
    max_epoch: 30
    shuffle: False
    optimizer: adam
    learning_rate: 1.e-3
    valid_freq: 1
    use_tfb: False
    metrics: [ 'acc', 'rmse' ]
    seed: 2025
    gpu: 0
  model_config:
    hidden_size: 64
    time_emb_size: 16
    num_layers: 2
    num_heads: 2
    mc_num_sample_per_step: 20
    loss_integral_num_sample_per_step: 20
    use_ln: False
    thinning:
      num_seq: 10
      num_sample: 1
      num_exp: 500 # number of i.i.d. Exp(intensity_bound) draws at one time in thinning algorithm
      look_ahead_time: 10
      patience_counter: 5 # the maximum iteration used in adaptive thinning
      over_sample_rate: 5
      num_samples_boundary: 5
      dtime_max: 5
      num_step_gen: 1


THP_gen:
  base_config:
    stage: gen
    backend: torch
    dataset_id: taxi
    runner_id: std_tpp
    model_id: THP # model name
    base_dir: './checkpoints/'
  trainer_config:
    batch_size: 256
    max_epoch: 1
  model_config:
    hidden_size: 64
    time_emb_size: 16
    num_layers: 2
    num_heads: 2
    mc_num_sample_per_step: 20
    loss_integral_num_sample_per_step: 20
    use_ln: False
#    pretrained_model_dir: ./checkpoints/2694_4384867712_230603-160544/models/saved_model
    thinning:
      num_seq: 10
      num_sample: 1
      num_exp: 500 # number of i.i.d. Exp(intensity_bound) draws at one time in thinning algorithm
      look_ahead_time: 10
      patience_counter: 5 # the maximum iteration used in adaptive thinning
      over_sample_rate: 5
      num_samples_boundary: 5
      dtime_max: 5
      num_step_gen: 10